spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/paperless_office?serverTimezone=Asia/Shanghai
    username: root
    password: Yx112358

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
